name       : haskell-edit-distance
version    : 0.2.2.1
release    : 2
source     :
    - http://hackage.haskell.org/package/edit-distance-0.2.2.1/edit-distance-0.2.2.1.tar.gz : 3e8885ee2f56ad4da940f043ae8f981ee2fe336b5e8e4ba3f7436cff4f526c4a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Optimized edit distances for fuzzy matching, including Levenshtein and restricted Damerau-Levenshtein algorithms.
description: |
    Optimized edit distances for fuzzy matching, including Levenshtein and restricted Damerau-Levenshtein algorithms.
builddeps  :
    - haskell-cabal-install
    - haskell-random-devel
rundeps    :
    - devel:
        - haskell-random-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
