name       : haskell-edit-distance
version    : 0.2.2.1
release    : 3
source     :
    - http://hackage.haskell.org/package/edit-distance-0.2.2.1/edit-distance-0.2.2.1.tar.gz : 3e8885ee2f56ad4da940f043ae8f981ee2fe336b5e8e4ba3f7436cff4f526c4a
license    : BSD-3-Clause
component  : programming.haskell
summary    : Optimized edit distances for fuzzy matching, including Levenshtein and restricted Damerau-Levenshtein algorithms.
description: |
    Optimized edit distances for fuzzy matching, including Levenshtein and restricted Damerau-Levenshtein algorithms.
builddeps  :
    - ghc-devel
    - haskell-random-devel
rundeps    :
    - devel :
        - haskell-random-devel
setup      : |
    cp $pkgfiles/1.cabal edit-distance.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
